{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "bda50be0-c04d-4250-b941-0cfb5e79e1a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ FAISS Index created and saved.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-07-11 18:27:52.503 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import numpy as np\n",
    "import faiss\n",
    "import pickle\n",
    "\n",
    "# Load your loan approval dataset\n",
    "df = pd.read_csv('Training Dataset.csv')\n",
    "df\n",
    "# Create knowledge chunks for retrieval\n",
    "chunks = []\n",
    "for col in df.columns:\n",
    "    sample_values = df[col].dropna().astype(str).sample(min(5, len(df[col].dropna())), random_state = 42).tolist()\n",
    "    chunk = f\"Column: {col}\\nSample Values: {sample_values}\\nDescription: Details related to {col} affecting loan approval.\"\n",
    "    chunks.append(chunk)\n",
    "\n",
    "#----------------------------------------\n",
    "# 3️⃣ Create Embeddings and Store FAISS Index\n",
    "#----------------------------------------\n",
    "model = SentenceTransformer('all-MiniLM-L6-v2')\n",
    "embeddings = model.encode(chunks)\n",
    "\n",
    "dimension = embeddings.shape[1]\n",
    "index = faiss.IndexFlatL2(dimension)\n",
    "index.add(np.array(embeddings))\n",
    "\n",
    "# Save index and chunks for reuse\n",
    "faiss.write_index(index, \"faiss_loan_index.index\")\n",
    "with open(\"chunks.pkl\", \"wb\") as f:\n",
    "    pickle.dump(chunks, f)\n",
    "\n",
    "print(\"✅ FAISS Index created and saved.\")\n",
    "\n",
    "#----------------------------------------\n",
    "# 4️⃣ Retrieval + Generation Function\n",
    "#----------------------------------------\n",
    "from openai import OpenAI\n",
    "client = OpenAI(api_key=\"YOUR_OPENAI_API_KEY\")\n",
    "\n",
    "# Load index and chunks back for querying\n",
    "index = faiss.read_index(\"faiss_loan_index.index\")\n",
    "with open(\"chunks.pkl\", \"rb\") as f:\n",
    "    chunks = pickle.load(f)\n",
    "\n",
    "def rag_query(user_query, top_k=3):\n",
    "    query_embedding = model.encode([user_query])\n",
    "    D, I = index.search(np.array(query_embedding), top_k)\n",
    "    retrieved_chunks = \"\\n\\n\".join([chunks[i] for i in I[0]])\n",
    "    \n",
    "    prompt = f\"\"\"\n",
    "You are a helpful assistant explaining loan approval data analysis.\n",
    "\n",
    "Context:\n",
    "{retrieved_chunks}\n",
    "\n",
    "Question:\n",
    "{user_query}\n",
    "\n",
    "Answer in clear, beginner-friendly language.\n",
    "\"\"\"\n",
    "    \n",
    "    completion = client.chat.completions.create(\n",
    "        model=\"gpt-4o-preview\",\n",
    "        messages=[\n",
    "            {\"role\": \"system\", \"content\": \"You are a helpful AI assistant.\"},\n",
    "            {\"role\": \"user\", \"content\": prompt}\n",
    "        ]\n",
    "    )\n",
    "    return completion.choices[0].message.content\n",
    "\n",
    "#----------------------------------------\n",
    "# 5️⃣ Streamlit Chatbot for UI (Optional)\n",
    "#----------------------------------------\n",
    "# Save this as app.py and run using: streamlit run app.py\n",
    "\n",
    "import streamlit as st\n",
    "\n",
    "st.title(\"💡 RAG Q&A Chatbot: Loan Approval Dataset\")\n",
    "user_question = st.text_input(\"Ask a question about the loan dataset:\")\n",
    "\n",
    "if user_question:\n",
    "    with st.spinner(\"Generating answer...\"):\n",
    "        answer = rag_query(user_question)\n",
    "        st.success(answer)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6ae81060-435a-4ef1-b194-203623a1a7a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: sentence-transformers in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (5.0.0)\n",
      "Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from sentence-transformers) (4.53.2)\n",
      "Requirement already satisfied: tqdm in c:\\programdata\\anaconda3\\lib\\site-packages (from sentence-transformers) (4.66.4)\n",
      "Requirement already satisfied: torch>=1.11.0 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from sentence-transformers) (2.7.1)\n",
      "Requirement already satisfied: scikit-learn in c:\\programdata\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.4.2)\n",
      "Requirement already satisfied: scipy in c:\\programdata\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.13.1)\n",
      "Requirement already satisfied: huggingface-hub>=0.20.0 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from sentence-transformers) (0.33.4)\n",
      "Requirement already satisfied: Pillow in c:\\programdata\\anaconda3\\lib\\site-packages (from sentence-transformers) (10.3.0)\n",
      "Requirement already satisfied: typing_extensions>=4.5.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from sentence-transformers) (4.11.0)\n",
      "Requirement already satisfied: filelock in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)\n",
      "Requirement already satisfied: requests in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.2)\n",
      "Requirement already satisfied: sympy>=1.13.3 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)\n",
      "Requirement already satisfied: setuptools in c:\\programdata\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (69.5.1)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from tqdm->sentence-transformers) (0.4.6)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2023.10.3)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from scikit-learn->sentence-transformers) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from scikit-learn->sentence-transformers) (2.2.0)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.7.4)\n"
     ]
    }
   ],
   "source": [
    "!pip install sentence-transformers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "8f551d9e-b336-4cc7-86df-0b7b9e3b1638",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting faiss-cpu\n",
      "  Downloading faiss_cpu-1.11.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)\n",
      "Requirement already satisfied: numpy<3.0,>=1.25.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from faiss-cpu) (1.26.4)\n",
      "Requirement already satisfied: packaging in c:\\programdata\\anaconda3\\lib\\site-packages (from faiss-cpu) (23.2)\n",
      "Downloading faiss_cpu-1.11.0-cp312-cp312-win_amd64.whl (15.0 MB)\n",
      "   ---------------------------------------- 0.0/15.0 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/15.0 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.1/15.0 MB 1.1 MB/s eta 0:00:14\n",
      "    --------------------------------------- 0.3/15.0 MB 3.5 MB/s eta 0:00:05\n",
      "   -- ------------------------------------- 0.8/15.0 MB 5.7 MB/s eta 0:00:03\n",
      "   --- ------------------------------------ 1.2/15.0 MB 6.1 MB/s eta 0:00:03\n",
      "   ---- ----------------------------------- 1.7/15.0 MB 7.0 MB/s eta 0:00:02\n",
      "   ----- ---------------------------------- 2.0/15.0 MB 7.5 MB/s eta 0:00:02\n",
      "   ------ --------------------------------- 2.4/15.0 MB 7.2 MB/s eta 0:00:02\n",
      "   ------- -------------------------------- 2.8/15.0 MB 7.7 MB/s eta 0:00:02\n",
      "   -------- ------------------------------- 3.1/15.0 MB 7.3 MB/s eta 0:00:02\n",
      "   --------- ------------------------------ 3.6/15.0 MB 7.9 MB/s eta 0:00:02\n",
      "   ---------- ----------------------------- 3.9/15.0 MB 7.5 MB/s eta 0:00:02\n",
      "   ----------- ---------------------------- 4.2/15.0 MB 7.7 MB/s eta 0:00:02\n",
      "   ------------ --------------------------- 4.6/15.0 MB 7.5 MB/s eta 0:00:02\n",
      "   ------------- -------------------------- 4.9/15.0 MB 7.7 MB/s eta 0:00:02\n",
      "   -------------- ------------------------- 5.3/15.0 MB 7.5 MB/s eta 0:00:02\n",
      "   -------------- ------------------------- 5.6/15.0 MB 7.4 MB/s eta 0:00:02\n",
      "   --------------- ------------------------ 5.9/15.0 MB 7.4 MB/s eta 0:00:02\n",
      "   ---------------- ----------------------- 6.0/15.0 MB 7.4 MB/s eta 0:00:02\n",
      "   ----------------- ---------------------- 6.4/15.0 MB 7.3 MB/s eta 0:00:02\n",
      "   ------------------ --------------------- 6.8/15.0 MB 7.4 MB/s eta 0:00:02\n",
      "   ------------------- -------------------- 7.1/15.0 MB 7.4 MB/s eta 0:00:02\n",
      "   ------------------- -------------------- 7.4/15.0 MB 7.3 MB/s eta 0:00:02\n",
      "   -------------------- ------------------- 7.7/15.0 MB 7.3 MB/s eta 0:00:02\n",
      "   --------------------- ------------------ 8.0/15.0 MB 7.2 MB/s eta 0:00:01\n",
      "   --------------------- ------------------ 8.2/15.0 MB 7.1 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 8.6/15.0 MB 7.2 MB/s eta 0:00:01\n",
      "   ----------------------- ---------------- 8.9/15.0 MB 7.1 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.0/15.0 MB 7.0 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.0/15.0 MB 7.0 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.3/15.0 MB 6.7 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.3/15.0 MB 6.7 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.3/15.0 MB 6.7 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 9.3/15.0 MB 6.7 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 9.7/15.0 MB 6.1 MB/s eta 0:00:01\n",
      "   -------------------------- ------------- 9.8/15.0 MB 6.1 MB/s eta 0:00:01\n",
      "   -------------------------- ------------- 10.1/15.0 MB 6.0 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 10.3/15.0 MB 6.1 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 10.4/15.0 MB 6.0 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 10.8/15.0 MB 6.0 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 10.9/15.0 MB 6.0 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 11.2/15.0 MB 5.9 MB/s eta 0:00:01\n",
      "   ------------------------------ --------- 11.5/15.0 MB 5.8 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 11.7/15.0 MB 5.7 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 12.0/15.0 MB 5.7 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 12.3/15.0 MB 5.7 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 12.7/15.0 MB 5.6 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 13.3/15.0 MB 5.7 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 13.8/15.0 MB 5.7 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 14.2/15.0 MB 5.8 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 14.6/15.0 MB 5.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.0/15.0 MB 5.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 15.0/15.0 MB 5.7 MB/s eta 0:00:00\n",
      "Installing collected packages: faiss-cpu\n",
      "Successfully installed faiss-cpu-1.11.0\n"
     ]
    }
   ],
   "source": [
    "!pip install faiss-cpu\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f6cf8668-e970-4d53-975a-4a9ae9810c55",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: huggingface_hub[hf_xet] in c:\\users\\vaish\\appdata\\roaming\\python\\python312\\site-packages (0.33.4)\n",
      "Requirement already satisfied: filelock in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (6.0.1)\n",
      "Requirement already satisfied: requests in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (2.32.2)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\programdata\\anaconda3\\lib\\site-packages (from huggingface_hub[hf_xet]) (4.11.0)\n",
      "Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface_hub[hf_xet])\n",
      "  Downloading hf_xet-1.1.5-cp37-abi3-win_amd64.whl.metadata (883 bytes)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from tqdm>=4.42.1->huggingface_hub[hf_xet]) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface_hub[hf_xet]) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface_hub[hf_xet]) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface_hub[hf_xet]) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests->huggingface_hub[hf_xet]) (2024.7.4)\n",
      "Downloading hf_xet-1.1.5-cp37-abi3-win_amd64.whl (2.7 MB)\n",
      "   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/2.7 MB 217.9 kB/s eta 0:00:13\n",
      "    --------------------------------------- 0.0/2.7 MB 326.8 kB/s eta 0:00:09\n",
      "   --- ------------------------------------ 0.3/2.7 MB 1.7 MB/s eta 0:00:02\n",
      "   ---------- ----------------------------- 0.7/2.7 MB 3.8 MB/s eta 0:00:01\n",
      "   ---------------- ----------------------- 1.1/2.7 MB 4.7 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 1.6/2.7 MB 5.2 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 2.0/2.7 MB 6.2 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 2.5/2.7 MB 6.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.7/2.7 MB 6.7 MB/s eta 0:00:00\n",
      "Installing collected packages: hf-xet\n",
      "Successfully installed hf-xet-1.1.5\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install huggingface_hub[hf_xet]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "8f5c8bb9-25c6-49f2-84ae-270c38890f8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting openai\n",
      "  Downloading openai-1.95.0-py3-none-any.whl.metadata (29 kB)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (4.2.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (1.9.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (0.26.0)\n",
      "Collecting jiter<1,>=0.4.0 (from openai)\n",
      "  Downloading jiter-0.10.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)\n",
      "Requirement already satisfied: pydantic<3,>=1.9.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (2.5.3)\n",
      "Requirement already satisfied: sniffio in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (1.3.0)\n",
      "Requirement already satisfied: tqdm>4 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.11 in c:\\programdata\\anaconda3\\lib\\site-packages (from openai) (4.11.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\programdata\\anaconda3\\lib\\site-packages (from anyio<5,>=3.5.0->openai) (3.7)\n",
      "Requirement already satisfied: certifi in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->openai) (2024.7.4)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\programdata\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->openai) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\programdata\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.14.6 in c:\\programdata\\anaconda3\\lib\\site-packages (from pydantic<3,>=1.9.0->openai) (2.14.6)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from tqdm>4->openai) (0.4.6)\n",
      "Downloading openai-1.95.0-py3-none-any.whl (755 kB)\n",
      "   ---------------------------------------- 0.0/755.6 kB ? eta -:--:--\n",
      "   --- ------------------------------------ 61.4/755.6 kB 3.2 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 419.8/755.6 kB 6.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 755.6/755.6 kB 6.8 MB/s eta 0:00:00\n",
      "Downloading jiter-0.10.0-cp312-cp312-win_amd64.whl (206 kB)\n",
      "   ---------------------------------------- 0.0/206.2 kB ? eta -:--:--\n",
      "   --------------------------------------- 206.2/206.2 kB 12.2 MB/s eta 0:00:00\n",
      "Installing collected packages: jiter, openai\n",
      "Successfully installed jiter-0.10.0 openai-1.95.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: The script openai.exe is installed in 'C:\\Users\\vaish\\AppData\\Roaming\\Python\\Python312\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n"
     ]
    }
   ],
   "source": [
    "!pip install openai"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
